Repository omu/xokul, pull requests merged in 2019-10, with the labels that each got.

#121 Mege dev into master
  app/controllers/meksis_controller.rb
  app/serializers/meksis/buildings_serializer.rb
  app/serializers/meksis/classrooms_serializer.rb
  app/serializers/meksis/main_place_types_serializer.rb
  app/serializers/meksis/sub_place_types_serializer.rb
  app/services/lib/services/meksis.rb
  config/routes.rb
Labels: chore

#122 Merge dev into master
  app/serializers/meksis/buildings_serializer.rb
  app/services/lib/services/meksis.rb
  db/encrypted_data/buildings.json.enc
  lib/support/support.rb
  lib/support/support/sensitive.rb
Labels: chore

#123 Merge dev into master
  app/serializers/meksis/buildings_serializer.rb
Labels: chore

#125 Fix attribute type in books serializer
  app/serializers/yoksis/resumes/books_serializer.rb
  lib/support/support/sensitive.rb
Labels: improvement

#126 Change attribute name in books serializer
  app/serializers/yoksis/resumes/books_serializer.rb
Labels: bug

#127 Merge dev into master
  app/serializers/yoksis/resumes/books_serializer.rb
Labels: improvement

#129 Merge dev into master
  app/services/lib/services/yoksis/endpoints/resumes.rb
Labels: bug, improvement
